### ISSUE TITLE
Typo in Sample.ipynb

### ISSUE THREAD

**Issue by katiedagon** [mnlevy1981/SE1_questions#1]
Thank you @mnlevy1981 for putting this together.

I noticed a small typo in `Sample.ipynb:`

`Below we have started to write a function to convert an array with units mmol/m^3 cm/s to Pg / cm^2 / s. All that is missing is the conversion factor itself, please determine the proper value and update the function.`

I believe it should say `Pg / cm^2 / yr` ?

**Comment by mnlevy1981** [comment]
Yes, thanks! I made this typo in like 20 different places, but apparently only fixed it in 19 of them :) Fixed in 186ac41
